
# screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# ablities
# shot
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
SUPER_CHARGE_TIME =  1.5 #sec

# scatter shot
SCATTER_SHOT_TIME = 9

# time stop
TIME_STOP_DURATION = 5 #sec

# pass though
PASS_THOUGH_DURATION = 8 #sec

# asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#common
LINE_WIDTH = 2

